"""
PlatformIO pre-build script: regenerates src/build_stamp.h with the current
local timestamp on every build, so the [BUILD:...] line emitted in $I
(see report.c::report_build_info) refreshes whenever you rebuild.

Why a generated header instead of touch+__DATE__/__TIME__?
SCons (which PlatformIO drives) detects "changed" by content hash, not
mtime — `os.utime`-ing report.c doesn't invalidate report.o. But writing
a different value into a header that report.c includes does: SCons sees
build_stamp.h changed → report.c gets recompiled → __DATE__/__TIME__
embedded in the new report.o reflect the actual compile moment.

We rewrite build_stamp.h unconditionally with current datetime. The file
content always differs between runs (timestamps include seconds), so
SCons always invalidates the dependent translation unit.
"""

Import("env")

import datetime
import pathlib

stamp_h = pathlib.Path(env.subst("$PROJECT_DIR")) / "src" / "build_stamp.h"
now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

stamp_h.write_text(
    "/* Auto-generated by scripts/touch_build_stamp.py — do not edit. */\n"
    "#pragma once\n"
    f'#define BUILD_TIMESTAMP "{now}"\n'
)

print(f"build-stamp: wrote {stamp_h.relative_to(env.subst('$PROJECT_DIR'))} = {now}")
