"""
PlatformIO pre-build script: regenerates src/build_stamp.h with the current
local timestamp AND git provenance on every build, so the [BUILD:...] line
emitted in $I (see report.c::report_build_info) refreshes whenever you
rebuild and tells you exactly which repo/branch/commit produced the firmware.

Why a generated header instead of touch+__DATE__/__TIME__?
SCons (which PlatformIO drives) detects "changed" by content hash, not
mtime - `os.utime`-ing report.c doesn't invalidate report.o. But writing
a different value into a header that report.c includes does: SCons sees
build_stamp.h changed -> report.c gets recompiled -> the new BUILD_TIMESTAMP
string is embedded in report.o.

report.c prints BUILD_TIMESTAMP verbatim inside [BUILD:...], so all the
provenance lives in this one string - no core/report.c change needed. We
rewrite build_stamp.h unconditionally; the content always differs between
runs (timestamps include seconds), so SCons always invalidates report.c.

Provenance captured:
  drv:<branch>@<short-sha>  - the driver repo (iMXRT1062) checkout
  grbl:<describe>           - the grbl submodule (usually detached HEAD, so
                              git describe --all gives heads/<branch> when on
                              a branch tip, else an abbreviated SHA); a -dirty
                              suffix flags uncommitted overlay edits
git is optional: if it is missing or this isn't a repo, the helper returns
"?" and the build still succeeds (timestamp-only stamp).
"""

Import("env")

import datetime
import pathlib
import subprocess


def git(*args, cwd):
    try:
        out = subprocess.check_output(["git", *args], cwd=str(cwd),
                                      stderr=subprocess.DEVNULL).decode().strip()
        # git refs can't contain " or \, but keep the C string literal safe regardless
        return out.replace("\\", "").replace('"', "") or "?"
    except Exception:
        return "?"


proj = pathlib.Path(env.subst("$PROJECT_DIR"))            # grblHAL_Teensy4
stamp_h = proj / "src" / "build_stamp.h"
now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def ref(cwd):
    # "<branch-or-tag>@<short-sha>" (+ "-dirty"), so the BUILD line distinguishes
    # commits, not just branch names. Submodules are usually detached HEAD, so the
    # name comes from `git describe --all` (heads/<branch> at a tip, else a tag/sha);
    # strip the heads/remotes prefix and append the short sha. If describe already
    # resolved to the sha (detached, no ref), don't repeat it.
    name = git("describe", "--all", "--always", "--dirty", cwd=cwd).replace("heads/", "").replace("remotes/", "")
    sha = git("rev-parse", "--short", "HEAD", cwd=cwd)
    return name if (sha == "?" or sha in name) else "{}@{}".format(name, sha)


drv = ref(proj)
grbl = ref(proj / "src" / "grbl")

stamp = "{} drv:{} grbl:{}".format(now, drv, grbl)

stamp_h.write_text(
    "/* Auto-generated by scripts/touch_build_stamp.py - do not edit. */\n"
    "#pragma once\n"
    '#define BUILD_TIMESTAMP "{}"\n'.format(stamp)
)

print("build-stamp: wrote {} = {}".format(stamp_h.relative_to(proj), stamp))
